# Generated by Django 5.2.8 on 2025-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='horas_totales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas totales de uso de la máquina.', max_digits=10),
        ),
    ]
