# Generated by Django 5.2.8 on 2025-11-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0002_maquinaria_horas_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
