# Generated by Django 5.2.8 on 2025-12-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(db_column='id_empresa', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_proyectos', to='empresas.empresa'),
        ),
    ]
