# Generated by Django 5.2.8 on 2025-11-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinarias', '0003_maquinaria_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id_alarma', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la causa o información de la alarma.', null=True)),
                ('tipo', models.CharField(help_text="Tipo de alarma: 'mantenimiento', 'proyecto', etc.", max_length=50)),
                ('nivel', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('crítica', 'Crítica')], default='baja', help_text='Nivel de severidad de la alarma.', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro', help_text='Fecha en la que se creó la alarma.')),
                ('vista', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del registro.')),
                ('maquina', models.ForeignKey(db_column='id_maquina', help_text='Máquina asociada a la alarma.', on_delete=django.db.models.deletion.CASCADE, related_name='alarmas', to='maquinarias.maquinaria')),
            ],
            options={
                'verbose_name': 'alarma',
                'verbose_name_plural': 'alarmas',
                'db_table': 'alarmas',
            },
        ),
    ]
