# Generated by Django 5.2.8 on 2025-11-25 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinarias', '0003_maquinaria_foto'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHorasMaquinaria',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha en que se registraron las horas trabajadas.')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, help_text='Número de horas trabajadas por la máquina en esa fecha.', max_digits=10)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el registro.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to='maquinarias.maquinaria')),
                ('proyecto', models.ForeignKey(blank=True, db_column='id_proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_horas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'registro_horas_maquinaria',
                'verbose_name_plural': 'registros_horas_maquinaria',
                'db_table': 'registros_horas_maquinaria',
            },
        ),
    ]
