# Generated by Django 5.2.8 on 2025-12-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0003_maquinaria_foto'),
        ('proyectos', '0004_alter_proyecto_empresa'),
        ('registros_horas_maquinaria', '0001_initial'),
        ('usuarios', '0003_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohorasmaquinaria',
            name='foto_horometro_final',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrohorasmaquinaria',
            name='foto_horometro_inicial',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrohorasmaquinaria',
            name='foto_planilla',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrohorasmaquinaria',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_usuario', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='registrohorasmaquinaria',
            name='maquina',
            field=models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.CASCADE, related_name='registros_maquina', to='maquinarias.maquinaria'),
        ),
        migrations.AlterField(
            model_name='registrohorasmaquinaria',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_column='id_proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_proyecto', to='proyectos.proyecto'),
        ),
    ]
