# Generated by Django 5.2.8 on 2025-12-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_horas_maquinaria', '0002_registrohorasmaquinaria_foto_horometro_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohorasmaquinaria',
            name='foto_horometro_final',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrohorasmaquinaria',
            name='foto_horometro_inicial',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrohorasmaquinaria',
            name='foto_planilla',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
