# Generated by Django 5.2.8 on 2025-11-23 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimientos_programados', '0001_initial'),
        ('maquinarias', '0002_maquinaria_horas_totales'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], help_text='Tipo de mantenimiento realizado.', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_mantenimiento', models.DateField()),
                ('horas_realizadas', models.PositiveIntegerField(db_column='horas_realizadas', help_text='Horas totales acumuladas de la máquina al momento del mantenimiento.')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mantenimiento_programado', models.ForeignKey(blank=True, db_column='id_programado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='mantenimientos_programados.mantenimientoprogramado')),
                ('maquina', models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='maquinarias.maquinaria')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimientos',
            },
        ),
    ]
