# Generated by Django 5.2.8 on 2025-11-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_mantenimiento_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='archivo',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='mantenimiento_programado',
        ),
    ]
