# Generated by Django 5.2.8 on 2025-11-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0003_rename_archivo_mantenimiento_foto_and_more'),
        ('mantenimientos_programados', '0002_alter_mantenimientoprogramado_tipo'),
        ('maquinarias', '0003_maquinaria_foto'),
        ('usuarios', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='programado',
            field=models.ForeignKey(blank=True, db_column='id_programado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_programados', to='mantenimientos_programados.mantenimientoprogramado'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='maquina',
            field=models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_maquina', to='maquinarias.maquinaria'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_usuario', to='usuarios.usuario'),
        ),
    ]
