# Generated by Django 5.2.8 on 2025-12-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0004_mantenimiento_programado_alter_mantenimiento_maquina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='horas_realizadas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas totales acumuladas de la máquina al momento del mantenimiento.', max_digits=10),
        ),
    ]
