# Generated by Django 5.2.8 on 2025-12-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0005_alter_mantenimiento_horas_realizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
