# Generated by Django 5.2.8 on 2025-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
