# Generated by Django 5.2.8 on 2025-12-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(default='empleado', max_length=100),
            preserve_default=False,
        ),
    ]
