# Generated by Django 5.2.8 on 2025-11-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinarias', '0003_maquinaria_foto'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoMaquinaria',
            fields=[
                ('id_proyecto_maquinaria', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, help_text='Fecha en que la máquina fue asignada al proyecto.')),
                ('horas', models.DecimalField(decimal_places=2, default=0, help_text='Horas totales pactadas de la máquina.', max_digits=10)),
                ('finalizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.CASCADE, related_name='maquinas_proyectos', to='maquinarias.maquinaria')),
                ('proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_maquinas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto-Maquinaria',
                'verbose_name_plural': 'Proyectos-Maquinaria',
                'db_table': 'proyecto_maquinaria',
            },
        ),
    ]
