# Generated by Django 5.2.8 on 2025-11-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectomaquinaria',
            old_name='horas',
            new_name='horas_acumuladas',
        ),
        migrations.AddField(
            model_name='proyectomaquinaria',
            name='horas_totales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas totales pactadas de la máquina.', max_digits=10),
        ),
    ]
