# Generated by Django 5.2.8 on 2025-11-24 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinarias', '0003_maquinaria_foto'),
        ('usuarios', '0002_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaVida',
            fields=[
                ('id_hoja', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquinaria', models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.CASCADE, related_name='hojas_vida', to='maquinarias.maquinaria')),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_vida_registradas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Hoja de Vida',
                'verbose_name_plural': 'Hojas de Vida',
                'db_table': 'hoja_vida',
            },
        ),
    ]
