# Generated by Django 5.2.8 on 2025-12-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojas_vida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojavida',
            name='archivo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
