# Generated by Django 5.2.8 on 2025-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('RESPONSABLE_DE_MANTENIMIENTO', 'Responsable de mantenimiento'), ('OPERADOR', 'Operador'), ('TECNICO_DE_MANTENIMIENTO', 'Tecnico de mantenimiento')], default='OPERADOR', max_length=50),
        ),
    ]
