# Generated by Django 5.2.8 on 2025-11-23 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinarias', '0002_maquinaria_horas_totales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoProgramado',
            fields=[
                ('id_programado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Ejemplo: Cambio de aceite, Engrase, Revisión general', max_length=50)),
                ('intervalo_horas', models.PositiveIntegerField(help_text='Horas de uso entre cada mantenimiento programado')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales del mantenimiento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_programados', to='maquinarias.maquinaria')),
            ],
            options={
                'verbose_name': 'Mantenimiento programado',
                'verbose_name_plural': 'Mantenimientos programados',
                'db_table': 'mantenimientos_programados',
                'ordering': ['id_programado'],
            },
        ),
    ]
