# Generated by Django 5.2.8 on 2025-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos_programados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('predictivo', 'Predictivo')], help_text='Ejemplo: Preventivo, predictivo', max_length=50),
        ),
    ]
