# Generated by Django 5.2.8 on 2025-12-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos_programados', '0002_alter_mantenimientoprogramado_tipo'),
        ('maquinarias', '0003_maquinaria_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientoprogramado',
            name='nombre',
            field=models.CharField(default='General', help_text='Nombre del mantenimiento programado (único por máquina)', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='mantenimientoprogramado',
            constraint=models.UniqueConstraint(fields=('maquina', 'nombre'), name='unique_nombre_por_maquina'),
        ),
    ]
