# Generated by Django 5.2.8 on 2025-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos_programados', '0003_mantenimientoprogramado_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='nombre',
            field=models.CharField(help_text='Nombre del mantenimiento programado (único por máquina)', max_length=100),
        ),
    ]
